### ISSUE TITLE
docs: Need pull_request_template

### ISSUE THREAD

**Issue by PritamBag** [wrappid/styles#95]
**Is your feature request related to a problem? Please describe.**
pull_request_template is missing in this repository

**Describe the solution you'd like**
There is a need for a pull_request_template, so adding such a template helps the user or contributor with a pull request

**Describe alternatives you've considered**
Adding a pull_request_template is the best solution for this, So adding a pull_request_template is needed

**Comment by PritamBag** [comment]
@anantakumarghosh please make sure the development branch is merged with main so that people can get the benefit of the pull request.

**Comment by anantakumarghosh** [comment]
> @anantakumarghosh please make sure the development branch is merged with main so that people can get the benefit of the pull request.

development branch is merged with main
